import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import { ThemeProvider } from '@/components/ThemeProvider'
import ClientProvider from '@/components/ClientProvider'
import FirebaseAuthProv from '@/components/FirebaseAuthProv'

const poppins = Poppins({ weight:['200', '400', '600', '700', '800'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClientProvider>
    <html lang="en">
    <body className={[poppins.className,'flex flex-col min-h-screen'].join(' ')}>
      <FirebaseAuthProv>
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >
        <Header />
        {children}
        </ThemeProvider>
      </FirebaseAuthProv>
      </body>
    </html>
    </ClientProvider>
  )
}
